baseURL = 'https://punaisetlaulut.net/'
locale = 'fi'
title = 'punaisetlaulut.net'
theme = "hugo-xmin"

[menu]
  [[menu.main]]
    name = "Koti"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Info"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Työväenlaulutorstait"
    url = "/categories/työväenlaulutorstai/"
    weight = 3

  [[menu.main]]
    name = "Levykokoelma"
    url = "/levykokoelma/"
    weight = 5


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
